# Moonwalk

# 1
[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 0, 0, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

# 2
[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 0, 0, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

# 3
[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 0, 0, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

# 4
[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 1, 1, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 0, 0, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

# 5
[[section]]
contact  = [1, 1, 1, 1]
duration = 6